import { c as createComponent } from './Navbar_D-cSPFBH.mjs';
import 'piccolore';
import { t as maybeRenderHead, B as renderTemplate } from './prerender_C3Md0h36.mjs';
import 'clsx';

const $$Footer = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$props, $$slots);
  Astro2.self = $$Footer;
  const { updatedDate, generator = "ISMR Content Sync" } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<footer data-pagefind-ignore class="guide-footer"> ${updatedDate && renderTemplate`<p>Page generated by ${generator} on ${updatedDate}. Content summarised from external technical sources for educational purposes.</p>`} <p style="margin-top: 1rem;"><a href="/" style="color: var(--accent);">⚙️ ISMR Home</a></p> <p style="margin-top:0.75rem;font-size:0.82rem;color:var(--text-secondary);"><a href="/legal/privacy/" style="color:var(--accent);">Privacy Policy</a> &nbsp;·&nbsp; <a href="/legal/terms/" style="color:var(--accent);">Terms of Service</a></p> </footer>`;
}, "/sessions/sharp-gifted-meitner/mnt/interactive scooter repair manuals - ISRM/src/components/Footer.astro", void 0);

export { $$Footer as $ };
