name: Deploy to Hetzner FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          cd ./public
          find . -type f -print0 | xargs -0 -I {} curl -k -u "$FTP_USERNAME:$FTP_PASSWORD" \
            -T "{}" "sftp://$FTP_SERVER:22/public_html/{}"
